version: 0.2  # Required for CodeBuild

phases:
  install:
    commands:
      - echo "Installing dependencies..."
  build:
    commands:
      - echo "Building..."
      - echo "Hello World"
  post_build:
    commands:
      - echo "Post-build steps..."
