version: 0.2

env:
  variables:
    # Set Maven home (adjust if using a custom path)
    MAVEN_HOME: "/usr/share/maven"
    # Add Maven to PATH
    PATH: "$MAVEN_HOME/bin:$PATH"

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - mvn --version  # Verify Maven is installed

  build:
    commands:
      - echo "Building with Maven..."
      - mvn clean install  # Runs Maven build + tests

  post_build:
    commands:
      - echo "Build completed!"
      - ls -l target/  # List generated artifacts (e.g., JAR/WAR)
