version: 0.2

env:

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - mvn --version  # Verify Maven is installed

  build:
    commands:
      - echo "Building with Maven..."
      - ./mvnw clean install  # Runs Maven build + tests

  post_build:
    commands:
      - echo "Build completed!"
      - ls -l target/  # List generated artifacts (e.g., JAR/WAR)
