version: 0.2

env:
  variables:
    TEST: "true"  # Example environment variable
phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - chmod +x mvnw  # Make sure the Maven wrapper is executable
      - ./mvnw --version  # Verify Maven is installed

  build:
    commands:
      - echo "Building with Maven..."
      - chmod +x mvnw  # Make sure the Maven wrapper is executable
      - ./mvnw clean install  # Runs Maven build + tests

  post_build:
    commands:
      - echo "Build completed!"
      - ls -l target/  # List generated artifacts (e.g., JAR/WAR)
