name: Java CI with Maven (Java 23)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    # Set up JDK 23 (Temurin distribution)
    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'
        cache: maven  # Caches Maven dependencies
    
    # Build with Maven (using Java 23)
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      env:
        JAVA_HOME: ${{ env.JAVA_HOME_23_X64 }}  # Explicitly use Java 23
    
    # Optional: Dependency graph submission
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
